### ISSUE TITLE
API Quota information

### ISSUE THREAD

**Issue by sideloading** [w0d4/yt-backup#11]
Hi, 

I was wondering if you had any API quota cost calculations for this project?

E.g. what sort of cost I am looking at for 
- Checking 1 channel
- Checking a playlist for new uploads
etc

If you don't have this info readily available, feel free to close the issue -- I don't want to burden you with it 😄

**Comment by w0d4** [comment]
That's a simple question without a concrete answer. 
I can give you todays numbers as example. 
I monitored 66 channels with around 27.000 videos two times today.
I refreshed all playlist two times today. 
Some of these channels have more than one playlist, since I monitor some non-public playlists. 
I added one channel with --all_meta. 
I verified 90 offline videos two times today. 
Until now, I downloaded 192 videos. 
1.516/10.000 quota used until now.

**Comment by sideloading** [comment]
Thank you!!
