### ISSUE TITLE
503 error not being handled

### ISSUE THREAD

**Issue by Zulux91** [w0d4/yt-backup#15]
There's some sort of not handled [503 error](https://pastebin.com/WvAtaSG1) while the script is running. For what I could dig around 503 seems more a Youtube's side error refusing to server the file or not being available at the moment. It's not specifically related to a single file since running the same command again after a few seconds or minutes have worked and downloaded the video so I'm unable to give anyway to reproduce the error.

Either way I made a simple search on the script and didn't found any 503 error related handling.

Perhaps flagging the file for later download on a next run and making sure it hasn't been included in the "archive.list" file would be a way to handle it?

**Comment by w0d4** [comment]
I pushed commit 595ef306d4af8b06c04962f4ae237122ff4bbe83
Since I have never seen a 503 error out there on youtube since archiving 27k videos, I have nothing in my logs.
So I searched youtube-dl issues and reddit and tried to match the right error message.
Normaly, youtube-dl should not push the video ID into the archive.list
But I also implemented a function which will remove a video ID from archive.list, in case it was added anyways.
This function will be called with the current video id when a HTTP 503 error happened.

**Comment by Zulux91** [comment]
I'm getting the script stopped because of [this error](https://pastebin.com/vyAR6grT).

Edit: Trying to run it after it crashed because the mentioned error, I'm getting [this one](https://pastebin.com/T3XUFUUD).

**Comment by w0d4** [comment]
With commit 7e5253d7059e41626ccd482cc0f62446d8b896e2 this should be gone

**Comment by Zulux91** [comment]
Ok, thanks! It's running again nicely.
