### ISSUE TITLE
get_video_duration(video_file) not finding file the file

### ISSUE THREAD

**Issue by Zulux91** [w0d4/yt-backup#17]
I'm [getting a crash](https://pastebin.com/XaFENCy0) in the script's function _get_video_duration(video_file)_ not being able to find the downloaded file. I'm guessing it's due to special characters in the path and name...?

How to replicate:  The script is failing while working on this video `lVXYxs7XAaY` from this channel `♥ Luz ASMR ♥ (UCPKmMwKSf-6oJVLI1hZNo1A)`. In my setup the channel and the id are the folder name, just as shown here.

The file in fact does exist, I've check it, it's something messing with the script.

**Comment by w0d4** [comment]
I assume the brackets in the file name are causing issues.
I will try to reproduce and escape brackets in filenames.

**Comment by w0d4** [comment]
May you share your naming template. I can really not reproduce it. It's working fine with this video on my side.

**Comment by Zulux91** [comment]
This is my channel name and the folder name:
`"channel_naming": "%channel_name (%channel_id)"`

And my file name:
`"naming-format": "%(upload_date)s - %(title)s - (%(duration)ss) [%(resolution)s] [%(id)s].%(ext)s"`

**Comment by w0d4** [comment]
Unfortunately, I cannot reproduce the issue.
But since download should not be stopped only because not being able to find filesize and resolution, I added a few mitigations in commit d55c008a61d91438d48cbdcb26b56a746e15b717
In case the resolution and file size cannot be found, the script should continue anyways.
You can see [here](https://pastebin.com/fTsJyLNp), that it's working for me with the same naming template and the same video.
Maybe you can try changing your naming template to something without brackets and braces in file and channel name for further analysis.

**Comment by Zulux91** [comment]
I've been getting that error randomly. Since it's working all well on your side and the logic has been fixed I can't ask for more. Gonna have to check my end since seems to be the cause. Thanks!
