### ISSUE TITLE
Script doesn't handle channel deletion after being added

### ISSUE THREAD

**Issue by Zulux91** [w0d4/yt-backup#18]
Yesterday I managed to add a channel and run the script in it, downloading 5 videos. Now, after trying to run it the channel has been deleted and [the script crashes](https://pastebin.com/NSzGPm9d) upon discovering it.

I really don't know how to replicate it because all the meta data is inside the database, since the channel was operative yesterday but is now deleted. This is the channel: `UCnZa9czZopV-NY_4AvzvOwA`. Maybe I can export the metadata? I'm not very use to handling databases but if you provide the commands I could.

Thanks for your support on this project.

**Comment by w0d4** [comment]
Thanks for providing the infos.
I will try how I can detect deleted channels from youtube-api and flag them in the database.
This will require me to update the data model, since this was initially not planned.

**Comment by w0d4** [comment]
Hi,

I pushed commit 071fe264054cdc255ede5e0fbbcb9726710cba79
It contains a first try of finding offline channels and disabling them.
It will be executed before every `python3 yt-backup.py run`
If you want to run it by hand first, try `python3 yt-backup.py verify_channels`
This will update your data model to v2. I tested it on my side and it seems fine.
What I couldn't test is the feature, that if a channel goes offline, all playlists will be set to unmonitored and all videos will be set to offline, since I don't own the metadata of the offline channel.

**Comment by Zulux91** [comment]
Well it moved from that channel and flagged as non available or offline, couldn't read as text went on very fast. It's running smoothly so far. Seems to be solved. I'll post if anything else occurs, but doesn't seem to be the case.

Thanks!
