### ISSUE TITLE
Ability to add/download single video

### ISSUE THREAD

**Issue by sideloading** [w0d4/yt-backup#5]
Some videos may be unlisted, and having the ability to add it to the database/download queue would be quite useful.

**Comment by w0d4** [comment]
I will implement this. Sounds useful.
Since there is no way to get a playlist id for a video from youtube, this will get a bit uncomortable for the user, since the user will be forced to include --channel_id and --playlist_id by hand.

Problem is, that the average user don't know the playlist_id from which a unlisted video comes from. So, another option is to add a function "add_unlisted_video". This will get the channel_id from youtube, adds the channel to database if not existing, gets the upload playlist for the channel, create it in database if not existing and set the state to unmonitored.
Than add the unlisted video to the uploaded playlist of the channel.

**Comment by w0d4** [comment]
Added this function with 7976fab0f6e73c53da8be71f568d65ea04cde039
You can use `python3 yt-backup.py add_video --video_id <video_id> --video_status unlisted` to add an unlisted video with it's channel.
See README for more options regarding add_video feature.
